In [2]:
import nba_api.stats.endpoints as stats
import nba_api.stats.static.players as players

import pandas as pd
pd.set_option('display.max_columns', None)

In [3]:
# Nikola Jokić
career = stats.playercareerstats.PlayerCareerStats(player_id='203999')
df = career.season_totals_regular_season.get_data_frame()

In [4]:
df.head()

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,203999,2015-16,00,1610612743,DEN,21.0,80,55,1733,307,600,0.512,28,84,0.333,154,190,0.811,181,379,560,189,79,50,104,208,796
1,203999,2016-17,00,1610612743,DEN,22.0,73,59,2038,494,854,0.578,45,139,0.324,188,228,0.825,212,506,718,359,61,55,171,214,1221
2,203999,2017-18,00,1610612743,DEN,23.0,75,73,2443,504,1010,0.499,111,280,0.396,266,313,0.850,195,608,803,458,90,61,210,212,1385
3,203999,2018-19,00,1610612743,DEN,24.0,80,80,2504,616,1206,0.511,83,270,0.307,289,352,0.821,228,637,865,580,108,55,248,228,1604
4,203999,2019-20,00,1610612743,DEN,25.0,73,73,2335,565,1071,0.528,80,255,0.314,246,301,0.817,166,545,711,512,85,44,226,222,1456

In [5]:
help(stats)
stats.commonplayerinfo.CommonPlayerInfo(player_id='203999')

Help on package nba_api.stats.endpoints in nba_api.stats:

NAME
    nba_api.stats.endpoints

PACKAGE CONTENTS
    _base
    _expected_data (package)
    _parsers (package)
    alltimeleadersgrids
    assistleaders
    assisttracker
    boxscoreadvancedv2
    boxscoreadvancedv3
    boxscoredefensivev2
    boxscorefourfactorsv2
    boxscorefourfactorsv3
    boxscorehustlev2
    boxscorematchupsv3
    boxscoremiscv2
    boxscoremiscv3
    boxscoreplayertrackv3
    boxscorescoringv2
    boxscorescoringv3
    boxscoresummaryv2
    boxscoresummaryv3
    boxscoretraditionalv2
    boxscoretraditionalv3
    boxscoreusagev2
    boxscoreusagev3
    commonallplayers
    commonplayerinfo
    commonplayoffseries
    commonteamroster
    commonteamyears
    cumestatsplayer
    cumestatsplayergames
    cumestatsteam
    cumestatsteamgames
    defensehub
    draftboard
    draftcombinedrillresults
    draftcombinenonstationaryshooting
    draftcombineplayeranthro
    draftcombinespotshooting
    draftcombinestats
    drafthistory
    dunkscoreleaders
    fantasywidget
    franchisehistory
    franchiseleaders
    franchiseplayers
    gamerotation
    glalumboxscoresimilarityscore
    homepageleaders
    homepagev2
    hustlestatsboxscore
    infographicfanduelplayer
    iststandings
    leaderstiles
    leaguedashlineups
    leaguedashoppptshot
    leaguedashplayerbiostats
    leaguedashplayerclutch
    leaguedashplayerptshot
    leaguedashplayershotlocations
    leaguedashplayerstats
    leaguedashptdefend
    leaguedashptstats
    leaguedashptteamdefend
    leaguedashteamclutch
    leaguedashteamptshot
    leaguedashteamshotlocations
    leaguedashteamstats
    leaguegamefinder
    leaguegamelog
    leaguehustlestatsplayer
    leaguehustlestatsteam
    leagueleaders
    leaguelineupviz
    leagueplayerondetails
    leagueseasonmatchups
    leaguestandings
    leaguestandingsv3
    matchupsrollup
    playbyplay
    playbyplayv2
    playbyplayv3
    playerawards
    playercareerbycollege
    playercareerbycollegerollup
    playercareerstats
    playercompare
    playerdashboardbyclutch
    playerdashboardbygamesplits
    playerdashboardbygeneralsplits
    playerdashboardbylastngames
    playerdashboardbyshootingsplits
    playerdashboardbyteamperformance
    playerdashboardbyyearoveryear
    playerdashptpass
    playerdashptreb
    playerdashptshotdefend
    playerdashptshots
    playerestimatedmetrics
    playerfantasyprofilebargraph
    playergamelog
    playergamelogs
    playergamestreakfinder
    playerindex
    playernextngames
    playerprofilev2
    playervsplayer
    playoffpicture
    scheduleleaguev2
    scheduleleaguev2int
    scoreboardv2
    scoreboardv3
    shotchartdetail
    shotchartleaguewide
    shotchartlineupdetail
    synergyplaytypes
    teamandplayersvsplayers
    teamdashboardbygeneralsplits
    teamdashboardbyshootingsplits
    teamdashlineups
    teamdashptpass
    teamdashptreb
    teamdashptshots
    teamdetails
    teamestimatedmetrics
    teamgamelog
    teamgamelogs
    teamgamestreakfinder
    teamhistoricalleaders
    teaminfocommon
    teamplayerdashboard
    teamplayeronoffdetails
    teamplayeronoffsummary
    teamvsplayer
    teamyearbyyearstats
    videodetails
    videodetailsasset
    videoevents
    videoeventsasset
    videostatus
    winprobabilitypbp

DATA
    __all__ = ['alltimeleadersgrids', 'assistleaders', 'assisttracker', 'b...

FILE
    /Users/jackwang/.local/share/virtualenvs/nba_project-Ul73S7DA/lib/python3.13/site-packages/nba_api/stats/endpoints/__init__.py

In [6]:
all_players_info = players.get_players()
all_players_id =[d['id'] for d in all_players_info]
all_players_id

[76001,
 76002,
 76003,
 51,
 1505,
 949,
 76005,
 76006,
 76007,
 203518,
 1630173,
 101165,
 76008,
 76009,
 76010,
 203112,
 76011,
 76012,
 200801,
 1629121,
 203919,
 149,
 203500,
 912,
 1628389,
 1629061,
 76015,
 202399,
 201167,
 1630534,
 200772,
 76016,
 201336,
 76017,
 201582,
 76018,
 203006,
 1629152,
 202374,
 76019,
 76020,
 1630583,
 203128,
 202332,
 200746,
 76021,
 1626146,
 724,
 2042,
 76022,
 201570,
 1629734,
 1641725,
 1630234,
 2349,
 1629638,
 76024,
 1628959,
 76028,
 1628960,
 1628386,
 706,
 1628443,
 202730,
 76027,
 2124,
 76025,
 951,
 1641851,
 2754,
 76029,
 200984,
 76030,
 201165,
 308,
 1747,
 1824,
 1630631,
 680,
 732,
 202329,
 200811,
 76034,
 2365,
 2431,
 101187,
 202079,
 76035,
 76036,
 1507,
 76037,
 944,
 246,
 202341,
 76040,
 1626147,
 72,
 76041,
 203937,
 76042,
 76043,
 98,
 76045,
 76046,
 201583,
 1000,
 335,
 76048,
 101149,
 76049,
 1628387,
 76050,
 1512,
 1630828,
 203507,
 1628961,
 203648,
 2546,
 1630175,
 21,
 201202,
 203544,
 1628384,
 203951,
 2737,
 76053,
 76054,
 2425,
 1627853,
 76055,
 2240,
 2772,
 76056,
 76057,
 769,
 76061,
 2220,
 353,
 200756,
 76060,
 1642379,
 76059,
 76062,
 76063,
 76064,
 2306,
 201589,
 76065,
 1628503,
 201600,
 355,
 173,
 76068,
 76069,
 1088,
 76070,
 76071,
 278,
 201571,
 200788,
 1134,
 76073,
 76074,
 1630166,
 138,
 76076,
 1895,
 76078,
 1630555,
 202970,
 201965,
 1629028,
 101235,
 1628962,
 203569,
 202337,
 76079,
 76080,
 1628407,
 1630641,
 76081,
 2053,
 76082,
 1630542,
 1628963,
 1642846,
 1641735,
 76084,
 76083,
 76085,
 1847,
 1753,
 203946,
 1858,
 2486,
 76089,
 1627758,
 452,
 1627735,
 1631116,
 200764,
 76090,
 1630163,
 1628366,
 76091,
 76092,
 1628964,
 1631094,
 1630217,
 76093,
 2556,
 76094,
 76095,
 1630625,
 1627760,
 76096,
 2571,
 76097,
 200826,
 200745,
 76098,
 76099,
 787,
 2057,
 76102,
 1631230,
 203084,
 76103,
 76105,
 76104,
 2440,
 1630567,
 76107,
 76106,
 76108,
 76109,
 1642964,
 76110,
 76111,
 76112,
 76113,
 2857,
 76114,
 1629628,
 2853,
 344,
 699,
 1003,
 468,
 600013,
 76117,
 76118,
 203115,
 101188,
 76119,
 101138,
 1628238,
 76120,
 1629646,
 1766,
 2370,
 76121,
 1641734,
 1642926,
 1628966,
 101212,
 2471,
 1499,
 2203,
 1642419,
 174,
 76123,
 76124,
 201587,
 1641878,
 76125,
 76126,
 2437,
 201573,
 76127,
 203382,
 76128,
 203145,
 1629647,
 76129,
 203078,
 76130,
 76131,
 2602,
 1627736,
 201563,
 76133,
 201958,
 1630699,
 76134,
 1133,
 76136,
 76137,
 76138,
 1641736,
 76139,
 76140,
 76141,
 201158,
 2294,
 76142,
 1628395,
 1952,
 2559,
 76143,
 76144,
 1627761,
 76145,
 76146,
 1627733,
 1886,
 203968,
 104,
 1736,
 203461,
 1120,
 712,
 76151,
 76148,
 76152,
 128,
 202728,
 76154,
 1627791,
 76155,
 76156,
 1642866,
 1631262,
 76157,
 76158,
 1629541,
 202722,
 76159,
 696,
 201976,
 1630180,
 1630189,
 204021,
 76160,
 76161,
 76162,
 1710,
 76163,
 2740,
 76164,
 76165,
 1497,
 76166,
 76167,
 203920,
 1628444,
 76168,
 1449,
 76170,
 76171,
 1629048,
 1641931,
 202687,
 202357,
 76172,
 1641710,
 76173,
 1641778,
 76174,
 204028,
 76175,
 76176,
 76180,
 76177,
 1806,
 76179,
 201971,
 2581,
 202392,
 1628469,
 200807,
 76182,
 76183,
 76184,
 101154,
 302,
 202339,
 1629833,
 76186,
 76187,
 76188,
 1628417,
 916,
 1548,
 203505,
 1629129,
 76189,
 76190,
 2800,
 76191,
 1631205,
 76192,
 2586,
 202711,
 203992,
 177,
 101106,
 1564,
 1629626,
 76195,
 1628413,
 1629716,
 76196,
 1630195,
 1627762,
 76197,
 76203,
 1641737,
 76198,
 1603,
 1629648,
 1121,
 1629067,
 76201,
 41,
 2588,
 1626164,
 511,
 202344,
 200767,
 76204,
 1916,
 1522,
 76206,
 2430,
 2414,
 76207,
 1953,
 76209,
 76210,
 2547,
 76211,
 1630527,
 76212,
 76213,
 1628449,
 1630547,
 2257,
 1631123,
 76214,
 1898,
 1477,
 1763,
 1628968,
 194,
 76217,
 1085,
 1629065,
 76219,
 671,
 76221,
 76222,
 76223,
 1863,
 76224,
 76225,
 200841,
 76226,
 202342,
 76227,
 76228,
 76229,
 202340,
 76233,
 76230,
 76231,
 76232,
 2214,
 762,
 1628396,
 1361,
 66,
 1765,
 1920,
 76237,
 1882,
 210,
 1631103,
 76238,
 76239,
 76240,
 1629714,
 76241,
 76242,
 76243,
 1631128,
 1629649,
 1642886,
 160,
 2452,
 76245,
 76246,
 76247,
 201147,
 2249,
 76248,
 76249,
 200758,
 2056,
 76250,
 783,
 76252,
 76253,
 1641779,
 1628969,
 1628970,
 76254,
 1628578,
 76255,
 1628515,
 76256,
 1629052,
 76257,
 76258,
 76259,
 76260,
 76261,
 1631167,
 201972,
 1629151,
 76262,
 1627763,
 76263,
 76264,
 201166,
 1629717,
 1628415,
 76265,
 202705,
 76266,
 418,
 1631232,
 1641780,
 2810,
 1626148,
 76284,
 201628,
 1628971,
 359,
 2245,
 76270,
 244,
 200793,
 201974,
 2484,
 2081,
 76272,
 76273,
 1871,
 76275,
 203913,
 1627759,
 76276,
 2208,
 1631112,
 1641738,
 2198,
 76278,
 76279,
 203485,
 992,
 203900,
 1479,
 1629650,
 76277,
 136,
 753,
 76282,
 76283,
 76286,
 200769,
 76285,
 1628425,
 2357,
 76268,
 1630535,
 1629718,
 1630602,
 1628972,
 76287,
 76288,
 1628973,
 1594,
 1627852,
 1642868,
 1629091,
 76289,
 76290,
 977,
 95,
 1628418,
 76291,
 76292,
 1629783,
 76293,
 76294,
 76295,
 1761,
 76296,
 76297,
 201978,
 76298,
 146,
 1641723,
 1934,
 672,
 203493,
 76300,
 76301,
 76302,
 76303,
 2469,
 203504,
 76304,
 202692,
 2766,
 101207,
 76305,
 76306,
 76307,
 76308,
 76309,
 197,
 76311,
 675,
 76313,
 1629126,
 76314,
 416,
 76316,
 76317,
 202221,
 76318,
 76319,
 2406,
 202364,
 76320,
 2866,
 1630215,
 348,
 2446,
 202710,
 1631219,
 202779,
 1641824,
 201182,
 101115,
 101198,
 76321,
 76322,
 76323,
 2560,
 76324,
 203998,
 1629719,
 679,
 262,
 1631288,
 76326,
 201979,
 101181,
 154,
 76328,
 76329,
 203484,
 76331,
 76330,
 76332,
 76333,
 76334,
 76335,
 76336,
 1641739,
 76337,
 948,
 1630267,
 922,
 76338,
 203477,
 1629962,
 76339,
 203991,
 202382,
 2073,
 1642928,
 1630176,
 76340,
 76341,
 2367,
 76342,
 76343,
 1642382,
 76344,
 76345,
 200760,
 76346,
 156,
 76348,
 713,
 1757,
 76350,
 76351,
 76352,
 1642267,
 201960,
 76353,
 2679,
 1131,
 1853,
 76355,
 1642269,
 76356,
 76357,
 76358,
 76359,
 1628975,
 2466,
 76360,
 76361,
 1713,
 1628976,
 203487,
 1630618,
 76362,
 76363,
 1627936,
 76364,
 208,
 201956,
 1642264,
 1630658,
 76365,
 767,
 76367,
 1509,
 76368,
 1626161,
 1628505,
 190,
 1628463,
 76370,
 1629958,
 1630608,
 76,
 1911,
 76373,
 2763,
 201596,
 76374,
 76375,
 76376,
 1472,
 1630577,
 1630551,
 76378,
 1631113,
 2199,
 201163,
 76379,
 76380,
 364,
 76382,
 76383,
 76384,
 1629147,
 384,
 1629597,
 76385,
 76386,
 203805,
 76387,
 432,
 2735,
 719,
 164,
 1629185,
 76391,
 1642279,
 76392,
 1627737,
 76393,
 76394,
 76395,
 1642353,
 57,
 1631108,
 202091,
 1626176,
 203902,
 1630528,
 203565,
 928,
 1630619,
 1631321,
 76397,
 76398,
 201947,
 1629109,
 203546,
 1641740,
 1721,
 1629634,
 1626262,
 203903,
 1628492,
 201964,
 1127,
 1629651,
 2049,
 1642383,
 76402,
 2043,
 76403,
 1629598,
 1628499,
 1642363,
 76404,
 1642270,
 76406,
 1569,
 1641730,
 76407,
 76408,
 76409,
 1629599,
 76410,
 76411,
 715,
 202708,
 76412,
 934,
 76413,
 76414,
 76415,
 902,
 1642268,
 2044,
 76416,
 76418,
 76421,
 1530,
 2260,
 2215,
 76419,
 1628381,
 200776,
 202395,
 1641879,
 1628380,
 1627858,
 201954,
 2555,
 76422,
 1629045,
 2173,
 306,
 1628435,
 76425,
 76426,
 76427,
 76428,
 201144,
 76429,
 55,
 1626192,
 76431,
 76432,
 101215,
 76433,
 76434,
 76438,
 2567,
 201161,
 76435,
 76436,
 76437,
 2241,
 1626188,
 1629076,
 1628429,
 76439,
 1631451,
 76440,
 1641645,
 204022,
 76442,
 1030,
 76443,
 76444,
 1630536,
 76441,
 76446,
 203142,
 76447,
 76448,
 895,
 76450,
 76451,
 76452,
 1627822,
 76453,
 76454,
 1627856,
 203955,
 76456,
 1526,
 76457,
 1641731,
 1641741,
 76458,
 76459,
 1432,
 202408,
 202326,
 600003,
 203496,
 1642907,
 76462,
 76463,
 76464,
 76465,
 203459,
 1628470,
 1544,
 76466,
 1642384,
 2037,
 201621,
 202348,
 1628249,
 76468,
 76469,
 76470,
 2343,
 76471,
 76472,
 201159,
 76473,
 76474,
 76475,
 1506,
 76476,
 76477,
 76478,
 76479,
 180,
 76481,
 76482,
 203109,
 1630622,
 1642385,
 1629633,
 1629600,
 76483,
 187,
 1907,
 76487,
 1630595,
 201967,
 76485,
 203099,
 1061,
 76488,
 76489,
 940,
 223,
 76492,
 209,
 2201,
 201191,
 688,
 203552,
 201939,
 687,
 76505,
 1642359,
 76496,
 76497,
 2223,
 76498,
 956,
 76499,
 76500,
 1498,
 1630700,
 2845,
 1380,
 2605,
 76502,
 203584,
 ...]

In [7]:
active_players_info = players.get_active_players()
active_players_id =[d['id'] for d in active_players_info]
active_players_info

[{'id': 1630173,
  'full_name': 'Precious Achiuwa',
  'first_name': 'Precious',
  'last_name': 'Achiuwa',
  'is_active': True},
 {'id': 203500,
  'full_name': 'Steven Adams',
  'first_name': 'Steven',
  'last_name': 'Adams',
  'is_active': True},
 {'id': 1628389,
  'full_name': 'Bam Adebayo',
  'first_name': 'Bam',
  'last_name': 'Adebayo',
  'is_active': True},
 {'id': 1630534,
  'full_name': 'Ochai Agbaji',
  'first_name': 'Ochai',
  'last_name': 'Agbaji',
  'is_active': True},
 {'id': 1630583,
  'full_name': 'Santi Aldama',
  'first_name': 'Santi',
  'last_name': 'Aldama',
  'is_active': True},
 {'id': 1641725,
  'full_name': 'Trey Alexander',
  'first_name': 'Trey',
  'last_name': 'Alexander',
  'is_active': True},
 {'id': 1629638,
  'full_name': 'Nickeil Alexander-Walker',
  'first_name': 'Nickeil',
  'last_name': 'Alexander-Walker',
  'is_active': True},
 {'id': 1628960,
  'full_name': 'Grayson Allen',
  'first_name': 'Grayson',
  'last_name': 'Allen',
  'is_active': True},
 {'id': 1628386,
  'full_name': 'Jarrett Allen',
  'first_name': 'Jarrett',
  'last_name': 'Allen',
  'is_active': True},
 {'id': 1630631,
  'full_name': 'Jose Alvarado',
  'first_name': 'Jose',
  'last_name': 'Alvarado',
  'is_active': True},
 {'id': 203937,
  'full_name': 'Kyle Anderson',
  'first_name': 'Kyle',
  'last_name': 'Anderson',
  'is_active': True},
 {'id': 1630828,
  'full_name': 'Alex Antetokounmpo',
  'first_name': 'Alex',
  'last_name': 'Antetokounmpo',
  'is_active': True},
 {'id': 203507,
  'full_name': 'Giannis Antetokounmpo',
  'first_name': 'Giannis',
  'last_name': 'Antetokounmpo',
  'is_active': True},
 {'id': 203648,
  'full_name': 'Thanasis Antetokounmpo',
  'first_name': 'Thanasis',
  'last_name': 'Antetokounmpo',
  'is_active': True},
 {'id': 1630175,
  'full_name': 'Cole Anthony',
  'first_name': 'Cole',
  'last_name': 'Anthony',
  'is_active': True},
 {'id': 1628384,
  'full_name': 'OG Anunoby',
  'first_name': 'OG',
  'last_name': 'Anunoby',
  'is_active': True},
 {'id': 1630166,
  'full_name': 'Deni Avdija',
  'first_name': 'Deni',
  'last_name': 'Avdija',
  'is_active': True},
 {'id': 1629028,
  'full_name': 'Deandre Ayton',
  'first_name': 'Deandre',
  'last_name': 'Ayton',
  'is_active': True},
 {'id': 1628963,
  'full_name': 'Marvin Bagley III',
  'first_name': 'Marvin',
  'last_name': 'Bagley III',
  'is_active': True},
 {'id': 1642846,
  'full_name': 'Ace Bailey',
  'first_name': 'Ace',
  'last_name': 'Bailey',
  'is_active': True},
 {'id': 1630163,
  'full_name': 'LaMelo Ball',
  'first_name': 'LaMelo',
  'last_name': 'Ball',
  'is_active': True},
 {'id': 1628366,
  'full_name': 'Lonzo Ball',
  'first_name': 'Lonzo',
  'last_name': 'Ball',
  'is_active': True},
 {'id': 1631094,
  'full_name': 'Paolo Banchero',
  'first_name': 'Paolo',
  'last_name': 'Banchero',
  'is_active': True},
 {'id': 1630217,
  'full_name': 'Desmond Bane',
  'first_name': 'Desmond',
  'last_name': 'Bane',
  'is_active': True},
 {'id': 1631230,
  'full_name': 'Dominick Barlow',
  'first_name': 'Dominick',
  'last_name': 'Barlow',
  'is_active': True},
 {'id': 203084,
  'full_name': 'Harrison Barnes',
  'first_name': 'Harrison',
  'last_name': 'Barnes',
  'is_active': True},
 {'id': 1630567,
  'full_name': 'Scottie Barnes',
  'first_name': 'Scottie',
  'last_name': 'Barnes',
  'is_active': True},
 {'id': 1642964,
  'full_name': 'Brooks Barnhizer',
  'first_name': 'Brooks',
  'last_name': 'Barnhizer',
  'is_active': True},
 {'id': 1629628,
  'full_name': 'RJ Barrett',
  'first_name': 'RJ',
  'last_name': 'Barrett',
  'is_active': True},
 {'id': 1629646,
  'full_name': 'Charles Bassey',
  'first_name': 'Charles',
  'last_name': 'Bassey',
  'is_active': True},
 {'id': 1642926,
  'full_name': 'Tamar Bates',
  'first_name': 'Tamar',
  'last_name': 'Bates',
  'is_active': True},
 {'id': 1642419,
  'full_name': 'Jamison Battle',
  'first_name': 'Jamison',
  'last_name': 'Battle',
  'is_active': True},
 {'id': 201587,
  'full_name': 'Nicolas Batum',
  'first_name': 'Nicolas',
  'last_name': 'Batum',
  'is_active': True},
 {'id': 203078,
  'full_name': 'Bradley Beal',
  'first_name': 'Bradley',
  'last_name': 'Beal',
  'is_active': True},
 {'id': 1642866,
  'full_name': 'Joan Beringer',
  'first_name': 'Joan',
  'last_name': 'Beringer',
  'is_active': True},
 {'id': 1630180,
  'full_name': 'Saddiq Bey',
  'first_name': 'Saddiq',
  'last_name': 'Bey',
  'is_active': True},
 {'id': 1629048,
  'full_name': 'Goga Bitadze',
  'first_name': 'Goga',
  'last_name': 'Bitadze',
  'is_active': True},
 {'id': 202687,
  'full_name': 'Bismack Biyombo',
  'first_name': 'Bismack',
  'last_name': 'Biyombo',
  'is_active': True},
 {'id': 1641710,
  'full_name': 'Anthony Black',
  'first_name': 'Anthony',
  'last_name': 'Black',
  'is_active': True},
 {'id': 203992,
  'full_name': 'Bogdan Bogdanović',
  'first_name': 'Bogdan',
  'last_name': 'Bogdanović',
  'is_active': True},
 {'id': 1641737,
  'full_name': 'Adem Bona',
  'first_name': 'Adem',
  'last_name': 'Bona',
  'is_active': True},
 {'id': 1626164,
  'full_name': 'Devin Booker',
  'first_name': 'Devin',
  'last_name': 'Booker',
  'is_active': True},
 {'id': 1628449,
  'full_name': 'Chris Boucher',
  'first_name': 'Chris',
  'last_name': 'Boucher',
  'is_active': True},
 {'id': 1628396,
  'full_name': 'Tony Bradley',
  'first_name': 'Tony',
  'last_name': 'Bradley',
  'is_active': True},
 {'id': 1631103,
  'full_name': 'Malaki Branham',
  'first_name': 'Malaki',
  'last_name': 'Branham',
  'is_active': True},
 {'id': 1631128,
  'full_name': 'Christian Braun',
  'first_name': 'Christian',
  'last_name': 'Braun',
  'is_active': True},
 {'id': 1642886,
  'full_name': 'Koby Brea',
  'first_name': 'Koby',
  'last_name': 'Brea',
  'is_active': True},
 {'id': 1628969,
  'full_name': 'Mikal Bridges',
  'first_name': 'Mikal',
  'last_name': 'Bridges',
  'is_active': True},
 {'id': 1628970,
  'full_name': 'Miles Bridges',
  'first_name': 'Miles',
  'last_name': 'Bridges',
  'is_active': True},
 {'id': 1628415,
  'full_name': 'Dillon Brooks',
  'first_name': 'Dillon',
  'last_name': 'Brooks',
  'is_active': True},
 {'id': 1641780,
  'full_name': 'Johni Broome',
  'first_name': 'Johni',
  'last_name': 'Broome',
  'is_active': True},
 {'id': 1628971,
  'full_name': 'Bruce Brown',
  'first_name': 'Bruce',
  'last_name': 'Brown',
  'is_active': True},
 {'id': 1627759,
  'full_name': 'Jaylen Brown',
  'first_name': 'Jaylen',
  'last_name': 'Brown',
  'is_active': True},
 {'id': 1641738,
  'full_name': 'Kobe Brown',
  'first_name': 'Kobe',
  'last_name': 'Brown',
  'is_active': True},
 {'id': 1628973,
  'full_name': 'Jalen Brunson',
  'first_name': 'Jalen',
  'last_name': 'Brunson',
  'is_active': True},
 {'id': 1642868,
  'full_name': 'Carter Bryant',
  'first_name': 'Carter',
  'last_name': 'Bryant',
  'is_active': True},
 {'id': 1628418,
  'full_name': 'Thomas Bryant',
  'first_name': 'Thomas',
  'last_name': 'Bryant',
  'is_active': True},
 {'id': 202710,
  'full_name': 'Jimmy Butler III',
  'first_name': 'Jimmy',
  'last_name': 'Butler III',
  'is_active': True},
 {'id': 1641824,
  'full_name': 'Matas Buzelis',
  'first_name': 'Matas',
  'last_name': 'Buzelis',
  'is_active': True},
 {'id': 1631288,
  'full_name': 'Jamal Cain',
  'first_name': 'Jamal',
  'last_name': 'Cain',
  'is_active': True},
 {'id': 203484,
  'full_name': 'Kentavious Caldwell-Pope',
  'first_name': 'Kentavious',
  'last_name': 'Caldwell-Pope',
  'is_active': True},
 {'id': 1641739,
  'full_name': 'Toumani Camara',
  'first_name': 'Toumani',
  'last_name': 'Camara',
  'is_active': True},
 {'id': 203991,
  'full_name': 'Clint Capela',
  'first_name': 'Clint',
  'last_name': 'Capela',
  'is_active': True},
 {'id': 1642928,
  'full_name': 'Dylan Cardwell',
  'first_name': 'Dylan',
  'last_name': 'Cardwell',
  'is_active': True},
 {'id': 1642382,
  'full_name': 'Branden Carlson',
  'first_name': 'Branden',
  'last_name': 'Carlson',
  'is_active': True},
 {'id': 1642267,
  'full_name': 'Bub Carrington',
  'first_name': 'Bub',
  'last_name': 'Carrington',
  'is_active': True},
 {'id': 1642269,
  'full_name': 'Devin Carter',
  'first_name': 'Devin',
  'last_name': 'Carter',
  'is_active': True},
 {'id': 1628975,
  'full_name': 'Jevon Carter',
  'first_name': 'Jevon',
  'last_name': 'Carter',
  'is_active': True},
 {'id': 1628976,
  'full_name': 'Wendell Carter Jr.',
  'first_name': 'Wendell',
  'last_name': 'Carter Jr.',
  'is_active': True},
 {'id': 1627936,
  'full_name': 'Alex Caruso',
  'first_name': 'Alex',
  'last_name': 'Caruso',
  'is_active': True},
 {'id': 1642264,
  'full_name': 'Stephon Castle',
  'first_name': 'Stephon',
  'last_name': 'Castle',
  'is_active': True},
 {'id': 1630658,
  'full_name': 'Colin Castleton',
  'first_name': 'Colin',
  'last_name': 'Castleton',
  'is_active': True},
 {'id': 1630577,
  'full_name': 'Julian Champagnie',
  'first_name': 'Julian',
  'last_name': 'Champagnie',
  'is_active': True},
 {'id': 1630551,
  'full_name': 'Justin Champagnie',
  'first_name': 'Justin',
  'last_name': 'Champagnie',
  'is_active': True},
 {'id': 1642353,
  'full_name': 'Cam Christie',
  'first_name': 'Cam',
  'last_name': 'Christie',
  'is_active': True},
 {'id': 1631108,
  'full_name': 'Max Christie',
  'first_name': 'Max',
  'last_name': 'Christie',
  'is_active': True},
 {'id': 1630619,
  'full_name': 'Moussa Cisse',
  'first_name': 'Moussa',
  'last_name': 'Cisse',
  'is_active': True},
 {'id': 1631321,
  'full_name': 'Sidy Cissoko',
  'first_name': 'Sidy',
  'last_name': 'Cissoko',
  'is_active': True},
 {'id': 1641740,
  'full_name': 'Jaylen Clark',
  'first_name': 'Jaylen',
  'last_name': 'Clark',
  'is_active': True},
 {'id': 1629634,
  'full_name': 'Brandon Clarke',
  'first_name': 'Brandon',
  'last_name': 'Clarke',
  'is_active': True},
 {'id': 203903,
  'full_name': 'Jordan Clarkson',
  'first_name': 'Jordan',
  'last_name': 'Clarkson',
  'is_active': True},
 {'id': 1629651,
  'full_name': 'Nic Claxton',
  'first_name': 'Nic',
  'last_name': 'Claxton',
  'is_active': True},
 {'id': 1642383,
  'full_name': 'Walter Clayton Jr.',
  'first_name': 'Walter',
  'last_name': 'Clayton Jr.',
  'is_active': True},
 {'id': 1642363,
  'full_name': 'Nique Clifford',
  'first_name': 'Nique',
  'last_name': 'Clifford',
  'is_active': True},
 {'id': 1642270,
  'full_name': 'Donovan Clingan',
  'first_name': 'Donovan',
  'last_name': 'Clingan',
  'is_active': True},
 {'id': 1641730,
  'full_name': 'Noah Clowney',
  'first_name': 'Noah',
  'last_name': 'Clowney',
  'is_active': True},
 {'id': 1629599,
  'full_name': 'Amir Coffey',
  'first_name': 'Amir',
  'last_name': 'Coffey',
  'is_active': True},
 {'id': 1642268,
  'full_name': 'Isaiah Collier',
  'first_name': 'Isaiah',
  'last_name': 'Collier',
  'is_active': True},
 {'id': 1628381,
  'full_name': 'John Collins',
  'first_name': 'John',
  'last_name': 'Collins',
  'is_active': True},
 {'id': 1628380,
  'full_name': 'Zach Collins',
  'first_name': 'Zach',
  'last_name': 'Collins',
  'is_active': True},
 {'id': 201144,
  'full_name': 'Mike Conley',
  'first_name': 'Mike',
  'last_name': 'Conley',
  'is_active': True},
 {'id': 1626192,
  'full_name': 'Pat Connaughton',
  'first_name': 'Pat',
  'last_name': 'Connaughton',
  'is_active': True},
 {'id': 1631451,
  'full_name': 'Javonte Cooke',
  'first_name': 'Javonte',
  'last_name': 'Cooke',
  'is_active': True},
 {'id': 1630536,
  'full_name': 'Sharife Cooper',
  'first_name': 'Sharife',
  'last_name': 'Cooper',
  'is_active': True},
 {'id': 1641731,
  'full_name': 'Bilal Coulibaly',
  'first_name': 'Bilal',
  'last_name': 'Coulibaly',
  'is_active': True},
 {'id': 1642907,
  'full_name': 'Cedric Coward',
  'first_name': 'Cedric',
  'last_name': 'Coward',
  'is_active': True},
 {'id': 1642384,
  'full_name': 'Isaiah Crawford',
  'first_name': 'Isaiah',
  'last_name': 'Crawford',
  'is_active': True},
 {'id': 1630595,
  'full_name': 'Cade Cunningham',
  'first_name': 'Cade',
  'last_name': 'Cunningham',
  'is_active': True},
 {'id': 201939,
  'full_name': 'Stephen Curry',
  'first_name': 'Stephen',
  'last_name': 'Curry',
  'is_active': True},
 {'id': 1642359,
  'full_name': 'Pacôme Dadiet',
  'first_name': 'Pacôme',
  'last_name': 'Dadiet',
  'is_active': True},
 {'id': 1630700,
  'full_name': 'Dyson Daniels',
  'first_name': 'Dyson',
  'last_name': 'Daniels',
  'is_active': True},
 {'id': 1642368,
  'full_name': "N'Faly Dante",
  'first_name': "N'Faly",
  'last_name': 'Dante',
  'is_active': True},
 {'id': 203076,
  'full_name': 'Anthony Davis',
  'first_name': 'Anthony',
  'last_name': 'Davis',
  'is_active': True},
 {'id': 1631120,
  'full_name': 'JD Davison',
  'first_name': 'JD',
  'last_name': 'Davison',
  'is_active': True},
 {'id': 201942,
  'full_name': 'DeMar DeRozan',
  'first_name': 'DeMar',
  'last_name': 'DeRozan',
  'is_active': True},
 {'id': 1642484,
  'full_name': 'RayJ Dennis',
  'first_name': 'RayJ',
  'last_name': 'Dennis',
  'is_active': True},
 {'id': 1628978,
  'full_name': 'Donte DiVincenzo',
  'first_name': 'Donte',
  'last_name': 'DiVincenzo',
  'is_active': True},
 {'id': 1631217,
  'full_name': 'Moussa Diabaté',
  'first_name': 'Moussa',
  'last_name': 'Diabaté',
  'is_active': True},
 {'id': 1642885,
  'full_name': 'Mohamed Diawara',
  'first_name': 'Mohamed',
  'last_name': 'Diawara',
  'is_active': True},
 {'id': 1641711,
  'full_name': 'Gradey Dick',
  'first_name': 'Gradey',
  'last_name': 'Dick',
  'is_active': True},
 {'id': 1630621,
  'full_name': 'Hunter Dickinson',
  'first_name': 'Hunter',
  'last_name': 'Dickinson',
  'is_active': True},
 {'id': 1631172,
  'full_name': 'Ousmane Dieng',
  'first_name': 'Ousmane',
  'last_name': 'Dieng',
  'is_active': True},
 {'id': 1642265,
  'full_name': 'Rob Dillingham',
  'first_name': 'Rob',
  'last_name': 'Dillingham',
  'is_active': True},
 {'id': 1629029,
  'full_name': 'Luka Dončić',
  'first_name': 'Luka',
  'last_name': 'Dončić',
  'is_active': True},
 {'id': 1629652,
  'full_name': 'Luguentz Dort',
  'first_name': 'Luguentz',
  'last_name': 'Dort',
  'is_active': True},
 {'id': 1630245,
  'full_name': 'Ayo Dosunmu',
  'first_name': 'Ayo',
  'last_name': 'Dosunmu',
  'is_active': True},
 {'id': 203083,
  'full_name': 'Andre Drummond',
  'first_name': 'Andre',
  'last_name': 'Drummond',
  'is_active': True},
 {'id': 1627739,
  'full_name': 'Kris Dunn',
  'first_name': 'Kris',
  'last_name': 'Dunn',
  'is_active': True},
 {'id': 1642346,
  'full_name': 'Ryan Dunn',
  'first_name': 'Ryan',
  'last_name': 'Dunn',
  'is_active': True},
 {'id': 201142,
  'full_name': 'Kevin Durant',
  'first_name': 'Kevin',
  'last_name': 'Durant',
  'is_active': True},
 {'id': 1631105,
  'full_name': 'Jalen Duren',
  'first_name': 'Jalen',
  'last_name': 'Duren',
  'is_active': True},
 {'id': 1642856,
  'full_name': 'Egor Dëmin',
  'first_name': 'Egor',
  'last_name': 'Dëmin',
  'is_active': True},
 {'id': 1631106,
  'full_name': 'Tari Eason',
  'first_name': 'Tari',
  'last_name': 'Eason',
  'is_active': True},
 {'id': 1641744,
  'full_name': 'Zach Edey',
  'first_name': 'Zach',
  'last_name': 'Edey',
  'is_active': True},
 {'id': 1642845,
  'full_name': 'VJ Edgecombe',
  'first_name': 'VJ',
  'last_name': 'Edgecombe',
  'is_active': True},
 {'id': 1630162,
  'full_name': 'Anthony Edwards',
  'first_name': 'Anthony',
  'last_name': 'Edwards',
  'is_active': True},
 {'id': 1642348,
  'full_name': 'Justin Edwards',
  'first_name': 'Justin',
  'last_name': 'Edwards',
  'is_active': True},
 {'id': 1631165,
  'full_name': 'Keon Ellis',
  'first_name': 'Keon',
  'last_name': 'Ellis',
  'is_active': True},
 {'id': 203954,
  'full_name': 'Joel Embiid',
  'first_name': 'Joel',
  'last_name': 'Embiid',
  'is_active': True},
 {'id': 1642855,
  'full_name': 'Noa Essengue',
  'first_name': 'Noa',
  'last_name': 'Essengue',
  'is_active': True},
 {'id': 1630623,
  'full_name': 'Tyson Etienne',
  'first_name': 'Tyson',
  'last_name': 'Etienne',
  'is_active': True},
 {'id': 1629234,
  'full_name': 'Drew Eubanks',
  'first_name': 'Drew',
  'last_name': 'Eubanks',
  'is_active': True},
 {'id': 1641787,
  'full_name': 'Tosan Evbuomwan',
  'first_name': 'Tosan',
  'last_name': 'Evbuomwan',
  'is_active': True},
 {'id': 203957,
  'full_name': 'Danté Exum',
  'first_name': 'Danté',
  'last_name': 'Exum',
  'is_active': True},
 {'id': 1642847,
  'full_name': 'Jeremiah Fears',
  'first_name': 'Jeremiah',
  'last_name': 'Fears',
  'is_active': True},
 {'id': 1642271,
  'full_name': 'Kyle Filipowski',
  'first_name': 'Kyle',
  'last_name': 'Filipowski',
  'is_active': True},
 {'id': 1627827,
  'full_name': 'Dorian Finney-Smith',
  'first_name': 'Dorian',
  'last_name': 'Finney-Smith',
  'is_active': True},
 {'id': 1642843,
  'full_name': 'Cooper Flagg',
  'first_name': 'Cooper',
  'last_name': 'Flagg',
  'is_active': True},
 {'id': 1642853,
  'full_name': 'Rasheer Fleming',
  'first_name': 'Rasheer',
  'last_name': 'Fleming',
  'is_active': True},
 {'id': 1642280,
  'full_name': 'Trentyn Flowers',
  'first_name': 'Trentyn',
  'last_name': 'Flowers',
  'is_active': True},
 {'id': 1631323,
  'full_name': 'Simone Fontecchio',
  'first_name': 'Simone',
  'last_name': 'Fontecchio',
  'is_active': True},
 {'id': 1628368,
  'full_name': "De'Aaron Fox",
  'first_name': "De'Aaron",
  'last_name': 'Fox',
  'is_active': True},
 {'id': 1642402,
  'full_name': 'Enrique Freeman',
  'first_name': 'Enrique',
  'last_name': 'Freeman',
  'is_active': True},
 {'id': 1642277,
  'full_name': 'Johnny Furphy',
  'first_name': 'Johnny',
  'last_name': 'Furphy',
  'is_active': True},
 {'id': 1629655,
  'full_name': 'Daniel Gafford',
  'first_name': 'Daniel',
  'last_name': 'Gafford',
  'is_active': True},
 {'id': 1642066,
  'full_name': 'Myron Gardner',
  'first_name': 'Myron',
  'last_name': 'Gardner',
  'is_active': True},
 {'id': 1629636,
  'full_name': 'Darius Garland',
  'first_name': 'Darius',
  'last_name': 'Garland',
  'is_active': True},
 {'id': 1630568,
  'full_name': 'Luka Garza',
  'first_name': 'Luka',
  'last_name': 'Garza',
  'is_active': True},
 {'id': 1641718,
  'full_name': 'Keyonte George',
  'first_name': 'Keyonte',
  'last_name': 'George',
  'is_active': True},
 {'id': 1642273,
  'full_name': 'Kyshawn George',
  'first_name': 'Kyshawn',
  'last_name': 'George',
  'is_active': True},
 {'id': 202331,
  'full_name': 'Paul George',
  'first_name': 'Paul',
  'last_name': 'George',
  'is_active': True},
 {'id': 1630581,
  'full_name': 'Josh Giddey',
  'first_name': 'Josh',
  'last_name': 'Giddey',
  'is_active': True},
 {'id': 1628983,
  'full_name': 'Shai Gilgeous-Alexander',
  'first_name': 'Shai',
  'last_name': 'Gilgeous-Alexander',
  'is_active': True},
 {'id': 1630264,
  'full_name': 'Anthony Gill',
  'first_name': 'Anthony',
  'last_name': 'Gill',
  'is_active': True},
 {'id': 1631221,
  'full_name': 'Collin Gillespie',
  'first_name': 'Collin',
  'last_name': 'Gillespie',
  'is_active': True},
 {'id': 203497,
  'full_name': 'Rudy Gobert',
  'first_name': 'Rudy',
  'last_name': 'Gobert',
  'is_active': True},
 {'id': 1642884,
  'full_name': 'Vladislav Goldin',
  'first_name': 'Vladislav',
  'last_name': 'Goldin',
  'is_active': True},
 {'id': 1642864,
  'full_name': 'Hugo González',
  'first_name': 'Hugo',
  'last_name': 'González',
  'is_active': True},
 {'id': 1630692,
  'full_name': 'Jordan Goodwin',
  'first_name': 'Jordan',
  'last_name': 'Goodwin',
  'is_active': True},
 {'id': 203932,
  'full_name': 'Aaron Gordon',
  'first_name': 'Aaron',
  'last_name': 'Gordon',
  'is_active': True},
 {'id': 201569,
  'full_name': 'Eric Gordon',
  'first_name': 'Eric',
  'last_name': 'Gordon',
  'is_active': True},
 {'id': 203924,
  'full_name': 'Jerami Grant',
  'first_name': 'Jerami',
  'last_name': 'Grant',
  'is_active': True},
 {'id': 1631260,
  'full_name': 'AJ Green',
  'first_name': 'AJ',
  'last_name': 'Green',
  'is_active': True},
 {'id': 203110,
  'full_name': 'Draymond Green',

In [8]:
career = stats.playercareerstats.PlayerCareerStats(player_id='1630173')
df = career.season_totals_regular_season.get_data_frame()
df.head()

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1630173,2020-21,00,1610612748,MIA,21.0,61,4,737,124,228,0.544,0,1,0.000,56,110,0.509,73,135,208,29,20,28,43,91,304
1,1630173,2021-22,00,1610612761,TOR,22.0,73,28,1725,265,603,0.439,56,156,0.359,78,131,0.595,146,327,473,82,37,41,84,151,664
2,1630173,2022-23,00,1610612761,TOR,23.0,55,12,1141,196,404,0.485,29,108,0.269,87,124,0.702,100,228,328,50,31,30,59,102,508
3,1630173,2023-24,00,1610612761,TOR,24.0,25,0,437,78,170,0.459,13,47,0.277,24,42,0.571,50,86,136,44,16,12,29,40,193
4,1630173,2023-24,00,1610612752,NYK,24.0,49,18,1187,157,299,0.525,13,50,0.260,45,70,0.643,141,210,351,53,30,56,54,103,372

In [9]:
active_players_career_stats = []

for player_id in active_players_id:
    print(player_id)
    career = stats.playercareerstats.PlayerCareerStats(player_id=player_id)
    df = career.season_totals_regular_season.get_data_frame()
    print(df)

1630173
   PLAYER_ID SEASON_ID LEAGUE_ID     TEAM_ID TEAM_ABBREVIATION  PLAYER_AGE  \
0    1630173   2020-21        00  1610612748               MIA        21.0
1    1630173   2021-22        00  1610612761               TOR        22.0
2    1630173   2022-23        00  1610612761               TOR        23.0
3    1630173   2023-24        00  1610612761               TOR        24.0
4    1630173   2023-24        00  1610612752               NYK        24.0
5    1630173   2023-24        00           0               TOT        24.0
6    1630173   2024-25        00  1610612752               NYK        25.0
7    1630173   2025-26        00  1610612758               SAC        26.0

   GP  GS   MIN  FGM  FGA  FG_PCT  FG3M  FG3A  FG3_PCT  FTM  FTA  FT_PCT  \
0  61   4   737  124  228   0.544     0     1    0.000   56  110   0.509
1  73  28  1725  265  603   0.439    56   156    0.359   78  131   0.595
2  55  12  1141  196  404   0.485    29   108    0.269   87  124   0.702
3  25   0   437   78  170   0.459    13    47    0.277   24   42   0.571
4  49  18  1187  157  299   0.525    13    50    0.260   45   70   0.643
5  74  18  1624  235  469   0.501    26    97    0.268   69  112   0.616
6  57  10  1170  164  327   0.502    10    36    0.278   41   69   0.594
7  48  32   973  144  288   0.500    16    54    0.296   39   74   0.527

   OREB  DREB  REB  AST  STL  BLK  TOV   PF  PTS
0    73   135  208   29   20   28   43   91  304
1   146   327  473   82   37   41   84  151  664
2   100   228  328   50   31   30   59  102  508
3    50    86  136   44   16   12   29   40  193
4   141   210  351   53   30   56   54  103  372
5   191   296  487   97   46   68   83  143  565
6   101   216  317   55   47   42   45   81  379
7    90   171  261   55   40   26   32   79  343
203500
    PLAYER_ID SEASON_ID LEAGUE_ID     TEAM_ID TEAM_ABBREVIATION  PLAYER_AGE  \
0      203500   2013-14        00  1610612760               OKC        20.0
1      203500   2014-15        00  1610612760               OKC        21.0
2      203500   2015-16        00  1610612760               OKC        22.0
3      203500   2016-17        00  1610612760               OKC        23.0
4      203500   2017-18        00  1610612760               OKC        24.0
5      203500   2018-19        00  1610612760               OKC        25.0
6      203500   2019-20        00  1610612760               OKC        26.0
7      203500   2020-21        00  1610612740               NOP        27.0
8      203500   2021-22        00  1610612763               MEM        28.0
9      203500   2022-23        00  1610612763               MEM        29.0
10     203500   2024-25        00  1610612745               HOU        31.0
11     203500   2025-26        00  1610612745               HOU        32.0

    GP  GS   MIN  FGM  FGA  FG_PCT  FG3M  FG3A  FG3_PCT  FTM  FTA  FT_PCT  \
0   81  20  1197   93  185   0.503     0     0    0.000   79  136   0.581
1   70  67  1771  217  399   0.544     0     2    0.000  103  205   0.502
2   80  80  2014  261  426   0.613     0     0    0.000  114  196   0.582
3   80  80  2389  374  655   0.571     0     1    0.000  157  257   0.611
4   76  76  2487  448  712   0.629     0     2    0.000  160  286   0.559
5   80  80  2669  481  809   0.595     0     2    0.000  146  292   0.500
6   63  63  1681  283  478   0.592     1     3    0.333  117  201   0.582
7   58  58  1605  189  308   0.614     0     3    0.000   60  135   0.444
8   76  75  1999  210  384   0.547     0     1    0.000  108  199   0.543
9   42  42  1133  157  263   0.597     0     1    0.000   47  129   0.364
10  58   3   794   91  167   0.545     0     2    0.000   43   93   0.462
11  32  11   730   70  139   0.504     0     0    0.000   47   81   0.580

    OREB  DREB  REB  AST  STL  BLK  TOV   PF   PTS
0    142   190  332   43   40   57   71  203   265
1    199   324  523   66   38   86   99  222   537
2    219   314  533   62   42   89   84  223   636
3    281   332  613   86   89   78  146  195   905
4    384   301  685   88   92   78  128  215  1056
5    391   369  760  124  117   76  135  204  1108
6    207   376  583  146   51   67   94  122   684
7    213   301  514  111   54   38   78  113   438
8    349   411  760  256   65   60  115  153   528
9    214   271  485   97   36   46   79   98   361
10   166   161  327   66   22   28   54   60   225
11   145   131  276   48   22   20   35   55   187
1628389
   PLAYER_ID SEASON_ID LEAGUE_ID     TEAM_ID TEAM_ABBREVIATION  PLAYER_AGE  \
0    1628389   2017-18        00  1610612748               MIA        20.0
1    1628389   2018-19        00  1610612748               MIA        21.0
2    1628389   2019-20        00  1610612748               MIA        22.0
3    1628389   2020-21        00  1610612748               MIA        23.0
4    1628389   2021-22        00  1610612748               MIA        24.0
5    1628389   2022-23        00  1610612748               MIA        25.0
6    1628389   2023-24        00  1610612748               MIA        26.0
7    1628389   2024-25        00  1610612748               MIA        27.0
8    1628389   2025-26        00  1610612748               MIA        28.0

   GP  GS   MIN  FGM   FGA  FG_PCT  FG3M  FG3A  FG3_PCT  FTM  FTA  FT_PCT  \
0  69  19  1368  174   340   0.512     0     7    0.000  129  179   0.721
1  82  28  1913  280   486   0.576     3    15    0.200  166  226   0.735
2  72  72  2417  440   790   0.557     2    14    0.143  264  382   0.691
3  64  64  2143  456   800   0.570     2     8    0.250  283  354   0.799
4  56  56  1825  406   729   0.557     0     6    0.000  256  340   0.753
5  75  75  2598  602  1114   0.540     1    12    0.083  324  402   0.806
6  71  71  2416  530  1017   0.521    15    42    0.357  292  387   0.755
7  78  78  2674  540  1113   0.485    79   221    0.357  251  328   0.765
8  48  48  1506  312   705   0.443    78   231    0.338  183  234   0.782

   OREB  DREB  REB  AST  STL  BLK  TOV   PF   PTS
0   118   263  381  101   32   41   66  138   477
1   165   432  597  184   71   65  121  203   729
2   176   559  735  368   82   93  204  182  1146
3   142   431  573  346   75   66  169  145  1197
4   137   427  564  190   80   44  148  171  1068
5   184   504  688  240   88   61  187  208  1529
6   159   578  737  278   81   66  162  159  1367
7   185   564  749  337   98   53  161  162  1410
8    99   376  475  134   49   34   89   79   885
1630534
   PLAYER_ID SEASON_ID LEAGUE_ID     TEAM_ID TEAM_ABBREVIATION  PLAYER_AGE  \
0    1630534   2022-23        00  1610612762               UTA        23.0
1    1630534   2023-24        00  1610612762               UTA        24.0
2    1630534   2023-24        00  1610612761               TOR        24.0
3    1630534   2023-24        00           0               TOT        24.0
4    1630534   2024-25        00  1610612761               TOR        25.0
5    1630534   2025-26        00  1610612761               TOR        25.0
6    1630534   2025-26        00  1610612751               BKN        25.0
7    1630534   2025-26        00           0               TOT        25.0

   GP  GS   MIN  FGM  FGA  FG_PCT  FG3M  FG3A  FG3_PCT  FTM  FTA  FT_PCT  \
0  59  22  1209  165  386   0.427    81   228    0.355   56   69   0.812
1  51  10  1003  106  249   0.426    47   142    0.331   15   20   0.750
2  27  18   638   72  184   0.391    15    69    0.217   22   36   0.611
3  78  28  1642  178  433   0.411    62   211    0.294   37   56   0.661
4  64  45  1739  266  534   0.498   101   253    0.399   34   48   0.708
5  42  13   650   72  170   0.424    12    65    0.185   25   29   0.862
6   1   0    16    0    3   0.000     0     0    0.000    0    0   0.000
7  43  13   667   72  173   0.416    12    65    0.185   25   29   0.862

   OREB  DREB  REB  AST  STL  BLK  TOV   PF  PTS
0    43    78  121   67   16   15   41   99  467
1    35    91  126   47   27   29   34   66  274
2    39    51   90   36   20   15   30   51  181
3    74   142  216   83   47   44   64  117  455
4    61   181  242   98   58   30   54  125  667
5    33    62   95   30   17   11   19   75  181
6     3     3    6    2    0    1    0    0    0
7    36    65  101   32   17   12   19   75  181
1630583
   PLAYER_ID SEASON_ID LEAGUE_ID     TEAM_ID TEAM_ABBREVIATION  PLAYER_AGE  \
0    1630583   2021-22        00  1610612763               MEM        21.0
1    1630583   2022-23        00  1610612763               MEM        22.0
2    1630583   2023-24        00  1610612763               MEM        23.0
3    1630583   2024-25        00  1610612763               MEM        24.0
4    1630583   2025-26        00  1610612763               MEM        25.0

   GP  GS   MIN  FGM  FGA  FG_PCT  FG3M  FG3A  FG3_PCT  FTM  FTA  FT_PCT  \
0  32   0   360   53  132   0.402     6    48    0.125   20   32   0.625
1  77  20  1682  247  525   0.470    94   266    0.353  108  144   0.750
2  61  35  1618  247  568   0.435   106   304    0.349   54   87   0.621
3  65  16  1660  313  648   0.483   120   326    0.368   65   94   0.691
4  43  11  1198  228  476   0.479    70   200    0.350   76  114   0.667

   OREB  DREB  REB  AST  STL  BLK  TOV   PF  PTS
0    33    54   87   21    6   10   16   36  132
1    85   286  371   97   45   48   60  143  696
2    72   280  352  138   43   54   69   89  654
3    94   322  416  188   52   29   71   76  811
4    67   220  287  126   37   31   55   69  602
1641725
   PLAYER_ID SEASON_ID LEAGUE_ID     TEAM_ID TEAM_ABBREVIATION  PLAYER_AGE  \
0    1641725   2024-25        00  1610612743               DEN        22.0
1    1641725   2025-26        00  1610612740               NOP        22.0

   GP  GS  MIN  FGM  FGA  FG_PCT  FG3M  FG3A  FG3_PCT  FTM  FTA  FT_PCT  OREB  \
0  24   0  117   13   41   0.317     3    17    0.176    3    4    0.75     1
1   5   0   42    6    9   0.667     2     3    0.667    0    0    0.00     0

   DREB  REB  AST  STL  BLK  TOV  PF  PTS
0    11   12   11    2    1    5  10   32
1     4    4    5    1    1    1   4   14
1629638
    PLAYER_ID SEASON_ID LEAGUE_ID     TEAM_ID TEAM_ABBREVIATION  PLAYER_AGE  \
0     1629638   2019-20        00  1610612740               NOP        21.0
1     1629638   2020-21        00  1610612740               NOP        22.0
2     1629638   2021-22        00  1610612740               NOP        23.0
3     1629638   2021-22        00  1610612762               UTA        23.0
4     1629638   2021-22        00           0               TOT        23.0
5     1629638   2022-23        00  1610612762               UTA        24.0
6     1629638   2022-23        00  1610612750               MIN        24.0
7     1629638   2022-23        00           0               TOT        24.0
8     1629638   2023-24        00  1610612750               MIN        25.0
9     1629638   2024-25        00  1610612750               MIN        26.0
10    1629638   2025-26        00  1610612737               ATL        27.0

    GP  GS   MIN  FGM  FGA  FG_PCT  FG3M  FG3A  FG3_PCT  FTM  FTA  FT_PCT  \
0   47   1   591   98  266   0.368    46   133    0.346   25   37   0.676
1   46  13  1007  192  458   0.419    76   219    0.347   48   66   0.727
2   50  19  1317  237  632   0.375    95   305    0.311   70   97   0.722
3   15   2   149   16   48   0.333    10    33    0.303   11   12   0.917
4   65  21  1466  253  680   0.372   105   338    0.311   81  109   0.743
5   36   3   528   83  170   0.488    35    87    0.402   27   39   0.692
6   23   0   356   48  125   0.384    26    72    0.361   13   21   0.619
7   59   3   884  131  295   0.444    61   159    0.384   40   60   0.667
8   82  20  1921  236  538   0.439   131   335    0.391   52   65   0.800
9   82  10  2073  270  616   0.438   141   370    0.381   92  118   0.780
10  54  47  1795  368  850   0.433   164   440    0.373  184  208   0.885

    OREB  DREB  REB  AST  STL  BLK  TOV   PF   PTS
0      9    75   84   89   17    8   54   57   267
1     13   131  144  102   47   22   69   88   508
2     36   128  164  139   41   19   85   88   639
3      1    22   23   17    5    4    8   15    53
4     37   150  187  156   46   23   93  103   692
5      8    51   59   76   24   14   45   58   228
6      7    35   42   32    8    7   10   30   135
7     15    86  101  108   32   21   55   88   363
8     35   132  167  204   64   42   76  143   655
9     54   211  265  223   50   34   99  139   773
10    32   163  195  200   63   33  110  118  1084
1628960
   PLAYER_ID SEASON_ID LEAGUE_ID     TEAM_ID TEAM_ABBREVIATION  PLAYER_AGE  \
0    1628960   2018-19        00  1610612762               UTA        23.0
1    1628960   2019-20        00  1610612763               MEM        24.0
2    1628960   2020-21        00  1610612763               MEM        25.0
3    1628960   2021-22        00  1610612749               MIL        26.0
4    1628960   2022-23        00  1610612749               MIL        27.0
5    1628960   2023-24        00  1610612756               PHX        28.0
6    1628960   2024-25        00  1610612756               PHX        29.0
7    1628960   2025-26        00  1610612756               PHX        30.0

   GP  GS   MIN  FGM  FGA  FG_PCT  FG3M  FG3A  FG3_PCT  FTM  FTA  FT_PCT  \
0  38   2   416   67  178   0.376    32    99    0.323   45   60   0.750
1  38   0   718  117  251   0.466    57   141    0.404   39   45   0.867
2  50  38  1260  173  414   0.418   107   274    0.391   79   91   0.868
3  66  61  1805  255  569   0.448   159   389    0.409   64   74   0.865
4  72  70  1972  245  557   0.440   146   366    0.399  114  126   0.905
5  75  74  2513  340  682   0.499   205   445    0.461  129  147   0.878
6  64   7  1544  219  489   0.448   149   350    0.426   93  114   0.816
7  35  26  1059  197  471   0.418   117   317    0.369   85  101   0.842

   OREB  DREB  REB  AST  STL  BLK  TOV   PF   PTS
0     3    20   23   25    6    6   33   47   211
1     8    77   85   52   10    2   33   53   330
2    19   141  160  108   46    8   48   71   532
3    32   190  222  100   46   18   43   96   733
4    61   176  237  163   62   14   72  117   750
5    48   247  295  227   69   45   95  157  1014
6    34   160  194  137   54   19   75   95   680
7    25    81  106  140   50   10   59   79   596
1628386
    PLAYER_ID SEASON_ID LEAGUE_ID     TEAM_ID TEAM_ABBREVIATION  PLAYER_AGE  \
0     1628386   2017-18        00  1610612751               BKN        20.0
1     1628386   2018-19        00  1610612751               BKN        21.0
2     1628386   2019-20        00  1610612751               BKN        22.0
3     1628386   2020-21        00  1610612751               BKN        23.0
4     1628386   2020-21        00  1610612739               CLE        23.0
5     1628386   2020-21        00           0               TOT        23.0
6     1628386   2021-22        00  1610612739               CLE        24.0
7     1628386   2022-23        00  1610612739               CLE        25.0
8     1628386   2023-24        00  1610612739               CLE        26.0
9     1628386   2024-25        00  1610612739               CLE        27.0
10    1628386   2025-26        00  1610612739               CLE        27.0

    GP  GS   MIN  FGM  FGA  FG_PCT  FG3M  FG3A  FG3_PCT  FTM  FTA  FT_PCT  \
0   72  31  1441  234  397   0.589     5    15    0.333  114  147   0.776
1   80  80  2096  335  568   0.590     6    45    0.133  197  278   0.709
2   70  64  1852  302  465   0.649     0     6    0.000  171  270   0.633
3   12   5   320   44   65   0.677     0     0    0.000   46   61   0.754
4   51  40  1544  254  417   0.609     6    19    0.316  158  229   0.690
5   63  45  1864  298  482   0.618     6    19    0.316  204  290   0.703
6   56  56  1810  369  545   0.677     1    10    0.100  165  233   0.708
7   68  68  2220  403  626   0.644     1    10    0.100  162  221   0.733
8   77  77  2442  519  819   0.634     0     6    0.000  233  314   0.742
9   82  82  2296  452  640   0.706     0     5    0.000  199  277   0.718
10  43  43  1175  248  398   0.623     1     9    0.111  131  175   0.749

    OREB  DREB  REB  AST  STL  BLK  TOV   PF   PTS
0    144   244  388   49   28   88   82  147   587
1    191   481  672  110   43  120  103  184   873
2    216   455  671  110   40   92   77  162   775
3     38    87  125   20    7   19   22   21   134
4    158   348  506   86   25   71   78   75   672
5    196   435  631  106   32   90  100   96   806
6    192   410  602   92   44   75   94   97   904
7    221   445  666  113   54   84   93  153   969
8    243   568  811  210   53   81  121  147  1271
9    216   582  798  158   77   73   97  127  1103
10   101   255  356   85   42   37   59   78   628
1630631
   PLAYER_ID SEASON_ID LEAGUE_ID     TEAM_ID TEAM_ABBREVIATION  PLAYER_AGE  \
0    1630631   2021-22        00  1610612740               NOP        24.0
1    1630631   2022-23        00  1610612740               NOP        25.0
2    1630631   2023-24        00  1610612740               NOP        26.0
3    1630631   2024-25        00  1610612740               NOP        27.0
4    1630631   2025-26        00  1610612740               NOP        27.0
5    1630631   2025-26        00  1610612752               NYK        27.0
6    1630631   2025-26        00           0               TOT        27.0

   GP  GS   MIN  FGM  FGA  FG_PCT  FG3M  FG3A  FG3_PCT  FTM  FTA  FT_PCT  \
0  54   1   834  131  294   0.446    32   110    0.291   36   53   0.679
1  61  10  1310  201  489   0.411    83   247    0.336   65   80   0.813
2  56   0  1028  142  345   0.412    78   207    0.377   35   52   0.673
3  56  23  1366  204  521   0.392   111   309    0.359   60   74   0.811
4  41   0   896  117  280   0.418    70   193    0.363   20   24   0.833
5   3   0    62   14   30   0.467    10    22    0.455    4    6   0.667
6  44   0   958  131  310   0.423    80   215    0.372   24   30   0.800

   OREB  DREB  REB  AST  STL  BLK  TOV   PF  PTS
0    25    75  100  152   71    7   40   73  330
1    28   113  141  186   67   10   81  125  550
2    25   103  128  117   59   15   40   89  397
3    27   109  136  259   74   14   86   91  579
4    16    98  114  128   37    4   47   80  324
5     0     6    6   11    7    1    4    9   42
6    16   104  120  139   44    5   51   89  366
203937
    PLAYER_ID SEASON_ID LEAGUE_ID     TEAM_ID TEAM_ABBREVIATION  PLAYER_AGE  \
0      203937   2014-15        00  1610612759               SAS        21.0
1      203937   2015-16        00  1610612759               SAS        22.0
2      203937   2016-17        00  1610612759               SAS        23.0
3      203937   2017-18        00  1610612759               SAS        24.0
4      203937   2018-19        00  1610612763               MEM        25.0
5      203937   2019-20        00  1610612763               MEM        26.0
6      203937   2020-21        00  1610612763               MEM        27.0
7      203937   2021-22        00  1610612763               MEM        28.0
8      203937   2022-23        00  1610612750               MIN        29.0
9      203937   2023-24        00  1610612750               MIN        30.0
10     203937   2024-25        00  1610612744               GSW        31.0
11     203937   2024-25        00  1610612748               MIA        31.0
12     203937   2024-25        00           0               TOT        31.0
13     203937   2025-26        00  1610612762               UTA        32.0
14     203937   2025-26        00  1610612763               MEM        32.0
15     203937   2025-26        00           0               TOT        32.0

    GP  GS   MIN  FGM  FGA  FG_PCT  FG3M  FG3A  FG3_PCT  FTM  FTA  FT_PCT  \
0   33   8   358   31   89   0.348     3    11    0.273    9   14   0.643
1   78  11  1245  138  295   0.468    12    37    0.324   62   83   0.747
2   72  14  1020   93  209   0.445    15    40    0.375   45   57   0.789
3   74  67  1978  231  438   0.527    19    57    0.333  104  146   0.712

KeyError: 'resultSet'